import { StyleSheet } from 'react-native';
import { colors, radii, shadows } from '../../theme/colors';

export const cartStyles = StyleSheet.create({
  container: {
    gap: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandBlueSoft,
  },
  title: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '700',
  },
  subtitle: {
    color: colors.inkMuted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  list: {
    gap: 12,
  },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    borderRadius: radii.medium,
    backgroundColor: colors.surface,
    padding: 14,
    ...shadows.card,
  },
  itemIcon: {
    width: 64,
    height: 64,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandBlueSoft,
    overflow: 'hidden',
  },
  itemImage: {
    width: '100%',
    height: '100%',
  },
  itemContent: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  itemTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  itemTitle: {
    flex: 1,
    color: colors.ink,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  itemMeta: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  itemWarningRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
  },
  itemWarningText: {
    flex: 1,
    color: '#8A5800',
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  itemFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 4,
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceMuted,
  },
  stepperButton: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonDisabled: {
    opacity: 0.55,
  },
  stepperValue: {
    minWidth: 22,
    textAlign: 'center',
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  itemLineTotal: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  removeButton: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summary: {
    gap: 12,
    padding: 18,
    borderRadius: radii.large,
    backgroundColor: colors.brandBlueSoft,
  },
  summaryTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '700',
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryCaption: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 3,
  },
  summaryIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.brandBlueLine,
  },
  divider: {
    height: 1,
    backgroundColor: colors.brandBlueLine,
  },
  checkoutButton: {
    height: 52,
    borderRadius: radii.pill,
    backgroundColor: colors.brandBlue,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    shadowColor: colors.brandBlue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 5,
  },
  checkoutButtonPressed: {
    transform: [{ scale: 0.97 }],
  },
  checkoutButtonDisabled: {
    backgroundColor: colors.inkSoft,
    shadowOpacity: 0,
    elevation: 0,
  },
  checkoutText: {
    color: colors.surface,
    fontWeight: '700',
  },
  availabilityWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: '#F1D391',
    backgroundColor: '#FFF8E8',
    padding: 12,
  },
  availabilityWarningText: {
    flex: 1,
    color: '#8A5800',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  securePaymentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    marginTop: -7,
    paddingHorizontal: 12,
  },
  securePaymentText: {
    flexShrink: 1,
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: '600',
    textAlign: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    gap: 12,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 24,
    backgroundColor: colors.surface,
    position: 'relative',
  },
  emptyIcon: {
    width: 78,
    height: 78,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandBlueSoft,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '700',
  },
  emptyText: {
    color: colors.inkMuted,
    textAlign: 'center',
    lineHeight: 20,
  },
  primaryButton: {
    height: 44,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    backgroundColor: colors.brandBlue,
  },
  primaryButtonText: {
    color: colors.surface,
    fontWeight: '700',
  },
});
