import { StyleSheet } from 'react-native';
import { colors, radii } from '../../theme/colors';

export const cartStyles = StyleSheet.create({
  container: {
    gap: 14,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandBlueSoft,
  },
  title: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '700',
  },
  subtitle: {
    color: colors.inkMuted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  list: {
    gap: 10,
  },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: 12,
    shadowColor: colors.brandBlue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 3,
  },
  itemIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandBlueSoft,
    overflow: 'hidden',
  },
  itemImage: {
    width: '100%',
    height: '100%',
  },
  itemContent: {
    flex: 1,
  },
  itemTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  itemMeta: {
    color: colors.inkMuted,
    fontSize: 11,
    marginTop: 3,
  },
  itemPrice: {
    color: colors.brandBlue,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 6,
  },
  itemActions: {
    alignItems: 'center',
    gap: 6,
  },
  quantityButton: {
    width: 26,
    height: 26,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  quantityButtonPressed: {
    transform: [{ scale: 0.92 }],
    backgroundColor: colors.brandBlueSoft,
  },
  quantity: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  removeButton: {
    width: 26,
    height: 26,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButtonPressed: {
    transform: [{ scale: 0.92 }],
    backgroundColor: colors.silverSoft,
  },
  summary: {
    gap: 10,
    padding: 14,
    borderRadius: radii.medium,
    backgroundColor: colors.brandBlueSoft,
    borderWidth: 1,
    borderColor: colors.brandBlueLine,
  },
  summaryTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: colors.line,
  },
  checkoutButton: {
    height: 48,
    borderRadius: radii.pill,
    backgroundColor: colors.brandBlue,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    shadowColor: colors.brandBlue,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 6,
  },
  checkoutButtonPressed: {
    transform: [{ scale: 0.97 }],
  },
  checkoutText: {
    color: colors.surface,
    fontWeight: '700',
  },
  emptyContainer: {
    alignItems: 'center',
    gap: 12,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 24,
    backgroundColor: colors.surface,
  },
  emptyIcon: {
    width: 78,
    height: 78,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandBlueSoft,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '700',
  },
  emptyText: {
    color: colors.inkMuted,
    textAlign: 'center',
    lineHeight: 20,
  },
  primaryButton: {
    height: 44,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    backgroundColor: colors.brandBlue,
  },
  primaryButtonText: {
    color: colors.surface,
    fontWeight: '700',
  },
});
