import { Platform, StyleSheet } from 'react-native';
import { colors, radii } from '../../theme/colors';

export const bottomNavHorizontalPadding = 16;
export const bottomNavDotSize = 11;

export const navigationStyles = StyleSheet.create({
  header: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    zIndex: 10,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    flexWrap: 'wrap',
    borderBottomWidth: 0,
    shadowColor: colors.primarySoft,
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.035,
    shadowRadius: 14,
    elevation: 2,
  },
  headerBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    maxWidth: Platform.OS === 'web' ? 320 : 260,
  },
  headerTitle: {
    color: colors.brandBlue,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 1.8,
  },
  cartBadge: {
    backgroundColor: colors.brandBlue,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    shadowColor: colors.brandBlue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  cartBadgePressed: {
    transform: [{ scale: 0.96 }],
  },
  cartCountBubble: {
    position: 'absolute',
    right: -3,
    top: -5,
    minWidth: 20,
    height: 20,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.brandAccent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  cartCountText: {
    color: colors.brandBlue,
    fontSize: 11,
    fontWeight: '900',
  },
  bottomNav: {
    position: 'absolute',
    left: 28,
    right: 28,
    bottom: 4,
    height: 86,
    justifyContent: 'flex-end',
    zIndex: 20,
  },
  bottomNavTrack: {
    height: 78,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    overflow: 'visible',
    backgroundColor: colors.surface,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: colors.brandBlueSoft,
    paddingHorizontal: bottomNavHorizontalPadding,
    shadowColor: colors.primarySoft,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 12,
  },
  bottomNavActiveIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 4,
  },
  bottomNavMovingDot: {
    position: 'absolute',
    left: 0,
    top: -1,
    width: bottomNavDotSize,
    height: bottomNavDotSize,
    borderRadius: radii.pill,
    backgroundColor: colors.brandBlue,
    shadowColor: colors.brandAccent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 5,
  },
  bottomNavIndent: {
    position: 'absolute',
    left: -(38 - bottomNavDotSize) / 2,
    top: -10,
    width: 38,
    height: 26,
    shadowColor: colors.brandBlue,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.035,
    shadowRadius: 4,
    elevation: 1,
    zIndex: 4,
  },
  bottomNavIndentArm: {
    position: 'absolute',
    top: 0,
    width: 25,
    height: 14,
    borderRadius: radii.pill,
    backgroundColor: colors.background,
  },
  bottomNavIndentArmLeft: {
    left: 0,
    transform: [{ rotate: '31deg' }],
  },
  bottomNavIndentArmRight: {
    right: 0,
    transform: [{ rotate: '-31deg' }],
  },
  bottomNavIndentTip: {
    position: 'absolute',
    left: 13,
    top: 10,
    width: 13,
    height: 13,
    borderRadius: 16,
    backgroundColor: colors.background,
  },
  bottomNavSelectionShadow: {
    position: 'absolute',
    bottom: 5,
    width: 25,
    height: 5,
    borderRadius: radii.pill,
    backgroundColor: colors.brandAccent,
    opacity: 0.09,
    shadowColor: colors.brandAccent,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 1,
    zIndex: -1,
  },
  bottomNavItem: {
    flex: 1,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    transform: [{ scale: 1 }],
    zIndex: 4,
  },
  bottomNavItemPressed: {
    transform: [{ scale: 0.95 }],
  },
});
