import { StyleSheet } from 'react-native';
import { colors, radii } from '../../theme/colors';

export const bottomNavHorizontalPadding = 16;
export const bottomNavDotSize = 11;

export const navigationStyles = StyleSheet.create({
  header: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 10,
    backgroundColor: 'transparent',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    overflow: 'visible',
  },
  headerGlass: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.surface,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  headerShadow: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -1,
    height: 6,
    backgroundColor: 'transparent',
    shadowColor: colors.primarySoft,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 4,
  },
  headerLogo: {
    width: 34,
    height: 34,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cartBadge: {
    backgroundColor: colors.surface,
    borderRadius: radii.small,
    borderWidth: 1,
    borderColor: colors.lineStrong,
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
  },
  cartBadgePressed: {
    transform: [{ scale: 0.94 }],
    backgroundColor: colors.surfaceMuted,
  },
  cartCountBubble: {
    position: 'absolute',
    right: -3,
    top: -5,
    minWidth: 20,
    height: 20,
    borderRadius: radii.pill,
    backgroundColor: colors.brandBlue,
    borderWidth: 2,
    borderColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  cartCountText: {
    color: colors.surface,
    fontSize: 11,
    fontWeight: '700',
  },
  bottomNav: {
    position: 'absolute',
    left: 28,
    right: 28,
    bottom: 4,
    height: 86,
    justifyContent: 'flex-end',
    zIndex: 20,
  },
  bottomNavTrack: {
    height: 78,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    overflow: 'visible',
    backgroundColor: colors.surface,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: colors.brandBlueSoft,
    paddingHorizontal: bottomNavHorizontalPadding,
    shadowColor: colors.primarySoft,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 12,
  },
  bottomNavActiveIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 6,
  },
  bottomNavIconGlyph: {
    lineHeight: 24,
    textAlign: 'center',
  },
  bottomNavSelectionShadow: {
    position: 'absolute',
    bottom: 7,
    width: 24,
    height: 5,
    borderRadius: radii.pill,
    backgroundColor: colors.primarySoft,
    opacity: 0.12,
    shadowColor: colors.primarySoft,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 7,
    elevation: 2,
    zIndex: -1,
  },
  bottomNavItem: {
    flex: 1,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    transform: [{ scale: 1 }],
    zIndex: 4,
  },
  bottomNavItemPressed: {
    transform: [{ scale: 0.95 }],
  },
});
