import { StyleSheet } from 'react-native';
import { colors, radii } from '../../theme/colors';

export const accountStyles = StyleSheet.create({
  accountCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.medium,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 10,
  },
  profilePage: {
    gap: 14,
  },
  socialHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  socialAvatarWrap: {
    position: 'relative',
  },
  socialAvatar: {
    width: 86,
    height: 86,
    borderRadius: 43,
    borderWidth: 3,
    borderColor: colors.surface,
    backgroundColor: colors.brandBlueSoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  socialAvatarBadge: {
    position: 'absolute',
    right: 2,
    bottom: 4,
    width: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: colors.brandBlue,
    borderWidth: 2,
    borderColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialStats: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 8,
  },
  profileStat: {
    minWidth: 54,
    alignItems: 'center',
    gap: 2,
  },
  profileStatValue: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  profileStatValueCompact: {
    fontSize: 12,
  },
  profileStatLabel: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: '800',
  },
  profilePencilButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialBio: {
    gap: 6,
  },
  socialBioText: {
    color: colors.inkMuted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  profileImportantStrip: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radii.medium,
    padding: 12,
    gap: 8,
  },
  importantInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  importantInfoText: {
    flex: 1,
    color: colors.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  profileActionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  profileActionButton: {
    flex: 1,
    height: 38,
    borderRadius: radii.small,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileActionText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '900',
  },
  profileHighlights: {
    flexDirection: 'row',
    gap: 12,
  },
  highlightItem: {
    width: 74,
    alignItems: 'center',
    gap: 6,
  },
  highlightCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  highlightLabel: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: '800',
  },
  profileTabs: {
    height: 42,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: colors.line,
  },
  profileTabActive: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderColor: colors.ink,
  },
  profileTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  postTile: {
    width: '32.6%',
    aspectRatio: 1,
    backgroundColor: colors.brandBlue,
    padding: 8,
    justifyContent: 'space-between',
  },
  postTileIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  postTileTitle: {
    color: colors.surface,
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 14,
  },
  postTileMeta: {
    color: colors.surface,
    fontSize: 10,
    fontWeight: '800',
  },
  emptyPosts: {
    minHeight: 150,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 18,
  },
  emptyPostsTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  emptyPostsText: {
    color: colors.inkMuted,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 18,
  },
  profileShell: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.medium,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 12,
  },
  settingsTopbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatarSettingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.brandBlueSoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarSettingsContent: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  avatarButtonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  avatarActionButton: {
    minHeight: 34,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.brandBlueLine,
    backgroundColor: colors.brandBlueSoft,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  avatarActionButtonDanger: {
    minHeight: 34,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: '#fecdd3',
    backgroundColor: '#fff1f2',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  avatarActionText: {
    color: colors.brandBlue,
    fontSize: 12,
    fontWeight: '900',
  },
  avatarActionTextDanger: {
    color: '#9f1239',
    fontSize: 12,
    fontWeight: '900',
  },
  settingsTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  settingsTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileAvatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.brandBlueSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: {
    color: colors.brandBlue,
    fontSize: 24,
    fontWeight: '900',
  },
  profileHeaderContent: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  profileSection: {
    backgroundColor: colors.surface,
    borderRadius: radii.small,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 12,
    gap: 12,
  },
  profileSectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  profileSectionTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  profileSectionHint: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },
  profileFieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileInfoItem: {
    flexGrow: 1,
    flexBasis: '46%',
    minWidth: 126,
    borderRadius: radii.small,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 10,
    gap: 3,
  },
  profileInfoLabel: {
    color: colors.inkSoft,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  profileInfoValue: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '900',
  },
  iconActionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.brandBlueLine,
    backgroundColor: colors.brandBlueSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editProfileForm: {
    gap: 10,
  },
  fieldWrapFull: {
    gap: 6,
  },
  multilineInput: {
    minHeight: 82,
    paddingTop: 10,
    textAlignVertical: 'top',
  },
  primaryButtonCompact: {
    flex: 1,
    height: 42,
    borderRadius: radii.pill,
    backgroundColor: colors.brandBlue,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  secondaryButtonCompact: {
    flex: 1,
    height: 42,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.brandBlueLine,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileMetricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  profileMetric: {
    flex: 1,
    minWidth: 130,
    borderRadius: radii.small,
    backgroundColor: colors.brandBlueSoft,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metricLabel: {
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  metricValue: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '900',
    marginTop: 2,
  },
  registerCard: {
    gap: 14,
  },
  accountName: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.ink,
  },
  accountEmail: {
    fontSize: 13,
    color: colors.inkMuted,
  },
  accountTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  dataGrid: {
    gap: 5,
    marginTop: 8,
  },
  dataText: {
    color: colors.inkMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  switchRow: {
    flexDirection: 'row',
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 4,
    marginBottom: 12,
  },
  switchButton: {
    flex: 1,
    height: 38,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  switchButtonActive: {
    backgroundColor: colors.brandBlue,
  },
  switchText: {
    color: colors.inkMuted,
    fontSize: 12,
    fontWeight: '900',
  },
  switchTextActive: {
    color: colors.surface,
  },
  input: {
    minHeight: 44,
    borderRadius: radii.small,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    color: colors.ink,
    paddingHorizontal: 12,
    fontSize: 13,
  },
  passwordInputWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  passwordInput: {
    paddingRight: 46,
  },
  passwordToggle: {
    position: 'absolute',
    right: 2,
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputLabel: {
    color: colors.ink,
    fontSize: 11,
    fontWeight: '900',
  },
  inputDisabled: {
    backgroundColor: colors.silverSoft,
    color: colors.inkMuted,
  },
  inlineRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'flex-end',
  },
  fieldWrap: {
    flex: 1,
    minWidth: 132,
    gap: 6,
  },
  genderFieldOpen: {
    minHeight: 238,
  },
  formSection: {
    backgroundColor: colors.surface,
    borderRadius: radii.small,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 12,
    gap: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  sectionKicker: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  sectionHint: {
    color: colors.inkMuted,
    fontSize: 11,
    fontWeight: '700',
    flexShrink: 1,
    textAlign: 'right',
  },
  selectTrigger: {
    minHeight: 44,
    borderRadius: radii.small,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  selectTriggerPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  selectValue: {
    flex: 1,
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
  },
  selectPlaceholder: {
    color: colors.inkSoft,
    fontWeight: '700',
  },
  selectOptions: {
    borderRadius: radii.small,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  selectOption: {
    minHeight: 42,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  selectOptionActive: {
    backgroundColor: colors.brandBlueSoft,
  },
  selectOptionPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  selectOptionText: {
    flex: 1,
    color: colors.inkMuted,
    fontSize: 13,
    fontWeight: '800',
  },
  selectOptionTextActive: {
    color: colors.brandBlue,
  },
  lookupButton: {
    width: 88,
    height: 44,
    borderRadius: radii.small,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandBlue,
  },
  lookupButtonText: {
    color: colors.surface,
    fontWeight: '900',
    fontSize: 12,
  },
  primaryButton: {
    height: 44,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    backgroundColor: colors.brandBlue,
    marginTop: 4,
  },
  secondaryButton: {
    height: 42,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.brandBlueLine,
    marginTop: 4,
  },
  buttonPressed: {
    transform: [{ scale: 0.98 }],
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: colors.surface,
    fontWeight: '900',
  },
  secondaryButtonText: {
    color: colors.brandBlue,
    fontWeight: '900',
  },
  message: {
    color: colors.inkMuted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  errorText: {
    color: '#9f1239',
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 16,
  },
  validationText: {
    color: '#9f1239',
    fontSize: 11,
    fontWeight: '700',
  },
});
